### ISSUE TITLE
Install Xdebug, by default.

### ISSUE THREAD

**Issue by mdwheele** [mdwheele/vm#48]

**Comment by elstamey** [comment]
import Xdebug
update the php.ini file

**Comment by mdwheele** [comment]
Sadly, can't do this in a sane way with the PHP binaries we compile. PECL would probably be the easiest way to do this via Puppet and it does not work with the compiled binaries because a lot of the extensions are not compiled in. That said, I'm working now on a PHP 7 and 5.6 SCL-based VM and I will include Xdebug there.
