### ISSUE TITLE
Drop port requirement for VM

### ISSUE THREAD

**Issue by jlmaners** [mdwheele/vm#52]
I'm having a heck of a time getting WordPress multisite working on the VM due to the fact WordPress doesn't support port numbers in the base URL of a multisite install. In addition, I am of the opinion that a more friendly URL scheme for development akin to http://local.dev or http://wordpress.local could promote a friendlier offering.

I see two initial paths development could take and am always open to discussion.

### Removal of Port Forwarding ###
The initial goal, if memory serves me, in using port forwarding was to ensure a black-box VM, inaccessible beyond the host machine. Vagrant supports private networking, giving the guest machine an address in a private address space that only the host machine can access. Using something in another subnet that what is used on campus is advisable so providing the guest machine with an address in the 192.168.X.X address space would probably be sufficient.

#### The simple approach ####
A user could customize their own `/etc/hosts` file to include the private IP address of the guest machine and a custom domain name. This could be a common name that could be used across projects (http://local.dev) or something more specific that could be manually changed.

#### More Complex Approach ####
Another approach would be to use a Vagrant plugin, like [Vagrant Host Manager](https://github.com/smdahlen/vagrant-hostmanager), that would allow each project/machine to customize their own development URL.

Appreciate thoughts, concerns, etc.

**Comment by mdwheele** [comment]
Quick notes for later:

* This virtual machine is used in contexts outside the University.
* It is already privately networked. Port forwarding was primarily done to support campus machines with policy that prevented services from squatting on low port ranges (80, 443). 
* If you address the guest machines by private IP address, they are by definition not accessible to world and you don't have to worry with port-forwarding. Port forwarding only necessary when used in context of `localhost`. At the time of implementation, it was not palatable to reference IPs directly so localhost was chosen and a port-forwarding solution was required that also explicated that ONLY the host machine was able to talk inward. VM could always talk outbound; not total blackbox.
* Managed hostnames are preferred but cannot be enforced in all cases. Any implementation using VHM must be flexible to know whether or not the plugin is installed before attempting to manage hosts.
* Hosts must be configurable at runtime through `config.yaml`.
* A discussion on what that looks like should be had, but there are already some sketches at https://github.com/mdwheele/vm/blob/master/config.dist.yaml#L21-L27. Also see how homestead does this: https://github.com/mdwheele/vm/blob/master/config.dist.yaml#L21-L27. I like this a lot.

**Comment by elstamey** [comment]
Isn't this resolved, @jlmaners ?

**Comment by mdwheele** [comment]
It's not, but I'm closing it. Changing hostname put the fire out, but recommended vagrant plugin does not work as advertised. I don't want to require additional configuration to make host mapping work as expected. Currently, manually adding a host entry to `/etc/hosts` resolves the issue. Make sure to point it at the private IP of your VM (set in `config.yaml`)

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
192.168.33.31   local.dev
```

**Comment by jlmaners** [comment]
@mdwheele the plugin mentioned in this issue or the one in the documentation? The plugin in the docs [Vagrant Ghost](https://github.com/10up/vagrant-ghost) has worked for me on both machines. Just as an FYI.
