### ISSUE TITLE
IP Address Mis-Match 

### ISSUE THREAD

**Issue by jlmaners** [mdwheele/vm#58]
There is an IP address mis-match that Audrey and I are noticing in using the VM. This only impacts us because the Riddick theme takes advantage of BrowserSync that performs best when pointed at the local private IP as opposed to local.dev.

https://github.com/mdwheele/vm/blob/master/config.dist.yaml#L2
vs
https://github.com/mdwheele/vm/blob/master/scripts/kraken.rb#L12

have different IP addresses. I'm guessing these should both be the same for consistency.

**Comment by mdwheele** [comment]
Changed. You can always override that in your local settings file.
