### ISSUE TITLE
The standard time is Fd up on the vm.

### ISSUE THREAD

**Issue by elstamey** [mdwheele/vm#59]
> sudo unlink /etc/localtime
    > sudo ln -s /usr/share/zoneinfo/US/Eastern /etc/localtime

    > date
    Tue Nov  3 14:54:44 EST 2015

**Comment by elstamey** [comment]
This is making my experience on the vm REALLY tough!

**Comment by mdwheele** [comment]
http://lkml.iu.edu/hypermail/linux/kernel/1510.3/02866.html

**Comment by elstamey** [comment]
I am not reading any of that man's comments.  There may be value in it, but I cannot even.
